### ISSUE TITLE
Cannot install dependencies

### ISSUE THREAD

**Issue by ghost** [SD3D/Filtracker#24]
When I install the plugin, all goes right, but when I start the configuration routine, after inserting the infill percentage, i click on install dependencies. Then it gives me an error like: Error: Command '/bin/bash -c 'sudo /usr/bin/apt-get update'' returned non-zero exit status 1

**Comment by davidfeeney** [comment]
Thanks for your feedback. The installation dependency part can be tricky and has only been tested on OctoPi configurations. 

First, please make sure you have an active connection to the internet at the time of install. If apt-get is located in another location you may need to create a branch that references the correct apt-get location for your os.
